# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('date', models.DateTimeField()),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published', models.IntegerField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Image', unique=True)),
            ],
            options={
                'db_table': 'produits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('username_canonical', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('email_canonical', models.CharField(max_length=255, unique=True)),
                ('enabled', models.IntegerField()),
                ('salt', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('locked', models.IntegerField()),
                ('expired', models.IntegerField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_requested_at', models.DateTimeField(blank=True, null=True)),
                ('roles', models.TextField()),
                ('credentials_expired', models.IntegerField()),
                ('credentials_expire_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'managed': True,
            },
        ),
    ]
